### ISSUE TITLE
Mobile Version Cards related

### ISSUE THREAD

**Issue by Yonasle** [fatmahussein/My-portfolio#8]
-Please Kindly include flex for your Grid cards.

**Comment by Kgomotso196** [comment]
I agree with @Yonasle . Also I'd suggest you kindly use classes instead of id's, since id's are specific to a single element whereas classes can be assigned to multiple elements on a page or throughout the website on your portfolio.

**Comment by God-Logic** [comment]
I am actually impressed with most of your work, I think outside the comments left by the other partners your work looks good.
